// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/notification/notification.proto

package vn_uprace_service_notify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8371b9b69ecbde2f, []int{4, 0}
}

type Alert struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Action               string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ActionLocKey         string   `protobuf:"bytes,5,opt,name=actionLocKey,proto3" json:"actionLocKey,omitempty"`
	LaunchImage          string   `protobuf:"bytes,6,opt,name=launchImage,proto3" json:"launchImage,omitempty"`
	LocKey               string   `protobuf:"bytes,7,opt,name=locKey,proto3" json:"locKey,omitempty"`
	TitleLocKey          string   `protobuf:"bytes,8,opt,name=titleLocKey,proto3" json:"titleLocKey,omitempty"`
	LocArgs              []string `protobuf:"bytes,9,rep,name=locArgs,proto3" json:"locArgs,omitempty"`
	TitleLocArgs         []string `protobuf:"bytes,10,rep,name=titleLocArgs,proto3" json:"titleLocArgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_8371b9b69ecbde2f, []int{0}
}

func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (m *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(m, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Alert) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Alert) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *Alert) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Alert) GetActionLocKey() string {
	if m != nil {
		return m.ActionLocKey
	}
	return ""
}

func (m *Alert) GetLaunchImage() string {
	if m != nil {
		return m.LaunchImage
	}
	return ""
}

func (m *Alert) GetLocKey() string {
	if m != nil {
		return m.LocKey
	}
	return ""
}

func (m *Alert) GetTitleLocKey() string {
	if m != nil {
		return m.TitleLocKey
	}
	return ""
}

func (m *Alert) GetLocArgs() []string {
	if m != nil {
		return m.LocArgs
	}
	return nil
}

func (m *Alert) GetTitleLocArgs() []string {
	if m != nil {
		return m.TitleLocArgs
	}
	return nil
}

type NotificationRequest struct {
	Tokens               []string        `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Platform             int32           `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Message              string          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Title                string          `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Topic                string          `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	Key                  string          `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Badge                int32           `protobuf:"varint,7,opt,name=badge,proto3" json:"badge,omitempty"`
	Category             string          `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Alert                *Alert          `protobuf:"bytes,9,opt,name=alert,proto3" json:"alert,omitempty"`
	Sound                string          `protobuf:"bytes,10,opt,name=sound,proto3" json:"sound,omitempty"`
	ContentAvailable     bool            `protobuf:"varint,11,opt,name=contentAvailable,proto3" json:"contentAvailable,omitempty"`
	ThreadID             string          `protobuf:"bytes,12,opt,name=threadID,proto3" json:"threadID,omitempty"`
	MutableContent       bool            `protobuf:"varint,13,opt,name=mutableContent,proto3" json:"mutableContent,omitempty"`
	Data                 *_struct.Struct `protobuf:"bytes,14,opt,name=data,proto3" json:"data,omitempty"`
	Image                string          `protobuf:"bytes,15,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NotificationRequest) Reset()         { *m = NotificationRequest{} }
func (m *NotificationRequest) String() string { return proto.CompactTextString(m) }
func (*NotificationRequest) ProtoMessage()    {}
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8371b9b69ecbde2f, []int{1}
}

func (m *NotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationRequest.Unmarshal(m, b)
}
func (m *NotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationRequest.Marshal(b, m, deterministic)
}
func (m *NotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationRequest.Merge(m, src)
}
func (m *NotificationRequest) XXX_Size() int {
	return xxx_messageInfo_NotificationRequest.Size(m)
}
func (m *NotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationRequest proto.InternalMessageInfo

func (m *NotificationRequest) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *NotificationRequest) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *NotificationRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NotificationRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NotificationRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NotificationRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NotificationRequest) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *NotificationRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *NotificationRequest) GetAlert() *Alert {
	if m != nil {
		return m.Alert
	}
	return nil
}

func (m *NotificationRequest) GetSound() string {
	if m != nil {
		return m.Sound
	}
	return ""
}

func (m *NotificationRequest) GetContentAvailable() bool {
	if m != nil {
		return m.ContentAvailable
	}
	return false
}

func (m *NotificationRequest) GetThreadID() string {
	if m != nil {
		return m.ThreadID
	}
	return ""
}

func (m *NotificationRequest) GetMutableContent() bool {
	if m != nil {
		return m.MutableContent
	}
	return false
}

func (m *NotificationRequest) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *NotificationRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type NotificationReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Counts               int32    `protobuf:"varint,2,opt,name=counts,proto3" json:"counts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationReply) Reset()         { *m = NotificationReply{} }
func (m *NotificationReply) String() string { return proto.CompactTextString(m) }
func (*NotificationReply) ProtoMessage()    {}
func (*NotificationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8371b9b69ecbde2f, []int{2}
}

func (m *NotificationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationReply.Unmarshal(m, b)
}
func (m *NotificationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationReply.Marshal(b, m, deterministic)
}
func (m *NotificationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationReply.Merge(m, src)
}
func (m *NotificationReply) XXX_Size() int {
	return xxx_messageInfo_NotificationReply.Size(m)
}
func (m *NotificationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationReply.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationReply proto.InternalMessageInfo

func (m *NotificationReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NotificationReply) GetCounts() int32 {
	if m != nil {
		return m.Counts
	}
	return 0
}

type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8371b9b69ecbde2f, []int{3}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=vn.uprace.service.notify.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8371b9b69ecbde2f, []int{4}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("vn.uprace.service.notify.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*Alert)(nil), "vn.uprace.service.notify.Alert")
	proto.RegisterType((*NotificationRequest)(nil), "vn.uprace.service.notify.NotificationRequest")
	proto.RegisterType((*NotificationReply)(nil), "vn.uprace.service.notify.NotificationReply")
	proto.RegisterType((*HealthCheckRequest)(nil), "vn.uprace.service.notify.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "vn.uprace.service.notify.HealthCheckResponse")
}

func init() {
	proto.RegisterFile("proto/notification/notification.proto", fileDescriptor_8371b9b69ecbde2f)
}

var fileDescriptor_8371b9b69ecbde2f = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x6f, 0x6f, 0xd3, 0x3e,
	0x10, 0xfe, 0x65, 0x6d, 0xba, 0xf6, 0xba, 0x3f, 0xfd, 0x79, 0x08, 0xac, 0x09, 0x89, 0x2a, 0x12,
	0xa8, 0x62, 0x2c, 0x93, 0x8a, 0x78, 0x03, 0xaf, 0xa6, 0x31, 0xc1, 0x34, 0xd4, 0x49, 0x29, 0x7f,
	0x5e, 0x22, 0xc7, 0xf1, 0xd2, 0x68, 0x6e, 0x1c, 0x62, 0x67, 0x52, 0x3f, 0x0f, 0x12, 0x5f, 0x88,
	0x2f, 0x84, 0x7c, 0x4e, 0x4a, 0x0b, 0xab, 0x34, 0xde, 0xf9, 0xb9, 0x7b, 0xee, 0xfc, 0xf8, 0xb9,
	0x33, 0x3c, 0x2d, 0x4a, 0x65, 0xd4, 0x49, 0xae, 0x4c, 0x76, 0x9d, 0x71, 0x66, 0x32, 0x95, 0xaf,
	0x81, 0x10, 0xf3, 0x84, 0xde, 0xe6, 0x61, 0x55, 0x94, 0x8c, 0x8b, 0x50, 0x8b, 0xf2, 0x36, 0xe3,
	0x22, 0x44, 0xd6, 0xe2, 0xf0, 0x71, 0xaa, 0x54, 0x2a, 0xc5, 0x09, 0xf2, 0xe2, 0xea, 0xfa, 0x44,
	0x9b, 0xb2, 0xe2, 0xc6, 0xd5, 0x05, 0xdf, 0xb7, 0xc0, 0x3f, 0x95, 0xa2, 0x34, 0xe4, 0x01, 0xf8,
	0x26, 0x33, 0x52, 0x50, 0x6f, 0xe8, 0x8d, 0x7a, 0x91, 0x03, 0x84, 0x40, 0x3b, 0x56, 0xc9, 0x82,
	0x6e, 0x61, 0x10, 0xcf, 0xe4, 0x10, 0xba, 0xba, 0x8a, 0x1d, 0xb9, 0x85, 0xf1, 0x25, 0x26, 0x0f,
	0xa1, 0xc3, 0xb8, 0xd5, 0x45, 0xdb, 0x98, 0xa9, 0x11, 0x09, 0x60, 0xc7, 0x9d, 0x3e, 0x28, 0x7e,
	0x29, 0x16, 0xd4, 0xc7, 0xec, 0x5a, 0x8c, 0x0c, 0xa1, 0x2f, 0x59, 0x95, 0xf3, 0xd9, 0xc5, 0x9c,
	0xa5, 0x82, 0x76, 0x90, 0xb2, 0x1a, 0xb2, 0xdd, 0xa5, 0xab, 0xdf, 0x76, 0xdd, 0xe5, 0xb2, 0x12,
	0xaf, 0xaf, 0x9b, 0x77, 0x5d, 0xe5, 0x4a, 0x88, 0x50, 0xd8, 0x96, 0x8a, 0x9f, 0x96, 0xa9, 0xa6,
	0xbd, 0x61, 0x6b, 0xd4, 0x8b, 0x1a, 0x68, 0x95, 0x35, 0x44, 0x4c, 0x03, 0xa6, 0xd7, 0x62, 0xc1,
	0xcf, 0x16, 0x1c, 0x4c, 0x56, 0x4c, 0x8f, 0xc4, 0xb7, 0x4a, 0x68, 0x63, 0xf5, 0x18, 0x75, 0x23,
	0x72, 0x4d, 0x3d, 0xac, 0xaa, 0x91, 0x75, 0xa8, 0x90, 0xcc, 0x5c, 0xab, 0x72, 0x8e, 0xce, 0xf9,
	0xd1, 0x12, 0x5b, 0x25, 0x73, 0xa1, 0xb5, 0x7d, 0xa1, 0x33, 0xaf, 0x81, 0xbf, 0x27, 0xd0, 0x5e,
	0x9d, 0x80, 0x8d, 0xaa, 0x22, 0xe3, 0xb5, 0x65, 0x0e, 0x90, 0x01, 0xb4, 0x6e, 0xc4, 0xa2, 0xf6,
	0xc8, 0x1e, 0x2d, 0x2f, 0x66, 0x49, 0x2a, 0xd0, 0x1a, 0x3f, 0x72, 0xc0, 0x2a, 0xe1, 0xcc, 0x88,
	0x54, 0x95, 0x8d, 0x2d, 0x4b, 0x4c, 0x5e, 0x81, 0xcf, 0xec, 0xe8, 0x69, 0x6f, 0xe8, 0x8d, 0xfa,
	0xe3, 0x27, 0xe1, 0xa6, 0x1d, 0x0a, 0x71, 0x43, 0x22, 0xc7, 0xb6, 0x17, 0x69, 0x55, 0xe5, 0x09,
	0x05, 0x27, 0x08, 0x01, 0x79, 0x0e, 0x03, 0xae, 0x72, 0x23, 0x72, 0x73, 0x7a, 0xcb, 0x32, 0xc9,
	0x62, 0x29, 0x68, 0x7f, 0xe8, 0x8d, 0xba, 0xd1, 0x5f, 0x71, 0x2b, 0xca, 0xcc, 0x4a, 0xc1, 0x92,
	0x8b, 0xb7, 0x74, 0xc7, 0x89, 0x6a, 0x30, 0x79, 0x06, 0x7b, 0xf3, 0xca, 0x58, 0xda, 0x99, 0x2b,
	0xa3, 0xbb, 0xd8, 0xe5, 0x8f, 0x28, 0x39, 0x82, 0x76, 0xc2, 0x0c, 0xa3, 0x7b, 0xa8, 0xfd, 0x51,
	0xe8, 0xb6, 0x3c, 0x6c, 0xb6, 0x3c, 0x9c, 0xe2, 0x96, 0x47, 0x48, 0xb2, 0x92, 0x33, 0xdc, 0xa9,
	0x7d, 0x27, 0x19, 0x41, 0x70, 0x0e, 0xff, 0xaf, 0x0f, 0xb5, 0x90, 0xb8, 0x28, 0xba, 0xe2, 0x5c,
	0x68, 0x8d, 0x1f, 0xa1, 0x1b, 0x35, 0xd0, 0x0e, 0x9b, 0xab, 0x2a, 0x37, 0xba, 0x1e, 0x69, 0x8d,
	0x82, 0x10, 0xc8, 0x7b, 0xc1, 0xa4, 0x99, 0x9d, 0xcd, 0x04, 0xbf, 0x69, 0x56, 0xc3, 0xf6, 0x71,
	0x26, 0xd6, 0x1f, 0xaa, 0x81, 0xc1, 0x0f, 0x0f, 0x0e, 0xd6, 0x0a, 0x74, 0xa1, 0x72, 0x2d, 0xc8,
	0x14, 0x3a, 0xda, 0x30, 0x53, 0xb9, 0x8b, 0xf7, 0xc6, 0x6f, 0x36, 0xcf, 0xe3, 0x8e, 0xf2, 0x70,
	0x6a, 0x29, 0x79, 0x3a, 0xc5, 0x16, 0x51, 0xdd, 0x2a, 0x78, 0x0d, 0xbb, 0x6b, 0x09, 0xd2, 0x87,
	0xed, 0x4f, 0x93, 0xcb, 0xc9, 0xd5, 0x97, 0xc9, 0xe0, 0x3f, 0x0b, 0xa6, 0xe7, 0xd1, 0xe7, 0x8b,
	0xc9, 0xbb, 0x81, 0x47, 0xf6, 0xa1, 0x3f, 0xb9, 0xfa, 0xf8, 0xb5, 0x09, 0x6c, 0x8d, 0x25, 0x74,
	0xd0, 0x9f, 0x05, 0x89, 0xa1, 0x3d, 0x15, 0x79, 0x42, 0x8e, 0x37, 0x4b, 0xba, 0xe3, 0x7b, 0x1c,
	0x1e, 0xdd, 0x97, 0x5e, 0xc8, 0xc5, 0x38, 0x87, 0x8e, 0x7b, 0x16, 0x49, 0xc0, 0xc7, 0xa7, 0x91,
	0x17, 0xf7, 0x74, 0xc0, 0xdd, 0x76, 0xfc, 0x4f, 0x7e, 0xc5, 0x1d, 0x5c, 0x95, 0x97, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x73, 0x33, 0x58, 0x0e, 0x61, 0x05, 0x00, 0x00,
}
